# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 2
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 3
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 4
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 5
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 6
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 6
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 7

# sbatch main.py --data-name hapt --shuffle --model-type tinyhar --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name hapt --shuffle --model-type mcnn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name hapt --shuffle --model-type attend --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name hapt --shuffle --model-type deepconvlstm --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name hapt --shuffle --model-type deepconvlstm_attn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name hapt --shuffle --model-type deepsense --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
# sbatch main.py --data-name hapt --shuffle --model-type globalfusion --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name hapt --shuffle --model-type aele --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name hapt --shuffle --model-type aele --seed 2 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name hapt --shuffle --model-type aele --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16



# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early




# sbatch main.py --data-name dsads --shuffle --model-type tinyhar --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dsads --shuffle --model-type mcnn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dsads --shuffle --model-type attend --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dsads --shuffle --model-type deepconvlstm --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dsads --shuffle --model-type deepconvlstm_attn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dsads --shuffle --model-type deepsense --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 25
# sbatch main.py --data-name dsads --shuffle --model-type globalfusion --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 25
sbatch main.py --data-name dsads --shuffle --model-type aele --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 25
sbatch main.py --data-name dsads --shuffle --model-type aele --seed 2 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 25
sbatch main.py --data-name dsads --shuffle --model-type aele --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 25




# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early


# sbatch main.py --data-name skodar --shuffle --model-type tinyhar --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name skodar --shuffle --model-type mcnn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name skodar --shuffle --model-type attend --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name skodar --shuffle --model-type deepconvlstm --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name skodar --shuffle --model-type deepconvlstm_attn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name skodar --shuffle --model-type deepsense --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
# sbatch main.py --data-name skodar --shuffle --model-type globalfusion --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name skodar --shuffle --model-type aele --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name skodar --shuffle --model-type aele --seed 2 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name skodar --shuffle --model-type aele --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16





# sbatch main.py --data-name skodar --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early

# sbatch main.py --data-name skodar --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early


# sbatch main.py --data-name skodar --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early

# sbatch main.py --data-name skodar --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early

# sbatch main.py --data-name skodar --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early


sbatch main.py --data-name skodar --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --residual-flag



sbatch main.py --data-name pamap2 --shuffle --model-type tinyhar --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
sbatch main.py --data-name pamap2 --shuffle --model-type mcnn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
sbatch main.py --data-name pamap2 --shuffle --model-type attend --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
sbatch main.py --data-name pamap2 --shuffle --model-type deepconvlstm --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
sbatch main.py --data-name pamap2 --shuffle --model-type deepconvlstm_attn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
#sbatch main.py --data-name pamap2 --shuffle --model-type deepsense --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name pamap2 --shuffle --model-type globalfusion --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name pamap2 --shuffle --model-type aele --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16






# sbatch main.py --data-name pamap2 --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name pamap2 --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name pamap2 --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-fuse-early
# sbatch main.py --data-name pamap2 --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early
# sbatch main.py --data-name pamap2 --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early
# sbatch main.py --data-name pamap2 --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-fuse-early


# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early

# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early


# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early



# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early














# sbatch main.py --data-name dg --shuffle --model-type tinyhar --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dg --shuffle --model-type mcnn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dg --shuffle --model-type attend --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dg --shuffle --model-type deepconvlstm --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dg --shuffle --model-type deepconvlstm_attn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128
# sbatch main.py --data-name dg --shuffle --model-type deepsense --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
# sbatch main.py --data-name dg --shuffle --model-type globalfusion --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name dg --shuffle --model-type aele --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name dg --shuffle --model-type aele --seed 2 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16
sbatch main.py --data-name dg --shuffle --model-type aele --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --fft-segments-length 16




# sbatch main.py --data-name motionsense --shuffle --model-type tinyhar --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type mcnn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type attend --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type deepconvlstm --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type deepconvlstm_attn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type deepsense --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
# sbatch main.py --data-name motionsense --shuffle --model-type globalfusion --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name motionsense --shuffle --model-type aele --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name motionsense --shuffle --model-type aele --seed 2 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name motionsense --shuffle --model-type aele --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16


# sbatch main.py --data-name motionsense --shuffle --model-type tinyhar --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type mcnn --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type attend --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type deepconvlstm --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type deepconvlstm_attn --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name motionsense --shuffle --model-type deepsense --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
# sbatch main.py --data-name motionsense --shuffle --model-type globalfusion --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
# sbatch main.py --data-name motionsense --shuffle --model-type aele --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16

sbatch main.py --data-name motionsense --shuffle --model-type globalfusion --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name motionsense --shuffle --model-type globalfusion --seed 2 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name motionsense --shuffle --model-type globalfusion --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16


# sbatch main.py --data-name mhealth --shuffle --model-type tinyhar --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type mcnn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type attend --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type deepconvlstm --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type deepconvlstm_attn --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type deepsense --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
# sbatch main.py --data-name mhealth --shuffle --model-type globalfusion --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name mhealth --shuffle --model-type aele --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name mhealth --shuffle --model-type aele --seed 2 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name mhealth --shuffle --model-type aele --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16

sbatch main.py --data-name mhealth --shuffle --model-type globalfusion --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name mhealth --shuffle --model-type globalfusion --seed 2 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
sbatch main.py --data-name mhealth --shuffle --model-type globalfusion --seed 3 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16

# sbatch main.py --data-name mhealth --shuffle --model-type tinyhar --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type mcnn --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type attend --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type deepconvlstm --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type deepconvlstm_attn --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256
# sbatch main.py --data-name mhealth --shuffle --model-type deepsense --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
# sbatch main.py --data-name mhealth --shuffle --model-type globalfusion --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16
# sbatch main.py --data-name mhealth --shuffle --model-type aele --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --fft-segments-length 16