

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal  
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal 
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal 
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal


sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-fuse-early --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal
sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.6 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal


