sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5



# ------------------------------------------------------------------------------------------------------------------


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5


# --------------------------------------------------------------------------------------------------------------



sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge channel --mixer-oration 0.5


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5



# --------------------------------------------------------------------------------------------------------------------------


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge channel --mixer-oration 0.5


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 --residual-flag


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 


sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5 --residual-flag

sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 50 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5


# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --residual-flag

# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 

# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --residual-flag


# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 

# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5 --residual-flag

# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge channel --mixer-oration 0.5 

# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 --residual-flag


# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5 



# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5 --residual-flag

# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation temporal --mixer-merge channel --mixer-oration 0.5 

# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 --residual-flag


# sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 256 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation temporal --mixer-merge temporal --mixer-oration 0.5 

# -------------------------------------------------------------------------------------------------
# # sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early

# # sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dg --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early


# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early



# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge channel --mixer-oration 0.5 --mixer-fuse-early






# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early

# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early


# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 4 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early



# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early
# # sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 5 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5 --mixer-fuse-early

# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5


# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.25
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.25
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.25

# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.25
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.25
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 2 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.25







# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.5


# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.25
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.25
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation both --mixer-merge temporal --mixer-oration 0.25

# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.25
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.25
# sbatch main.py --data-name dsads --shuffle --model-type mixermlp --seed 4 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 25 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 3 --mixer-representation fft --mixer-merge temporal --mixer-oration 0.25
