
# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 12 --mixer-mlp-expansion-factor 1.0 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 12 --fft-segments-length 12 --mixer-mlp-expansion-factor 1.0 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5




sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5



sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 32 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal --mixer-oration 0.5

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 32 --mixer-mlp-expansion-factor 0.2 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel --mixer-oration 0.5


# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7 --mixer-fuse-early

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7 --mixer-fuse-early

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7 --mixer-fuse-early

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7 --mixer-fuse-early

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7 --mixer-fuse-early

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7 --mixer-fuse-early

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 32 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7 --mixer-fuse-early

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 16 --fft-segments-length 32 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7 --mixer-fuse-early

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 32 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 10 --fft-segments-length 32 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 16 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 24 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 32 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 32 --mixer-mlp-expansion-factor 0.3 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 14 --fft-segments-length 12 --mixer-mlp-expansion-factor 1.0 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal --mixer-oration 0.7

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 14 --fft-segments-length 12 --mixer-mlp-expansion-factor 1.0 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel --mixer-oration 0.7 

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 14 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 14 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.5 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel




# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.8 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.8 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel 

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.8 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 8 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.8 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel 


# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.9 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.9 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel 

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.9 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 6 --fft-segments-length 12 --mixer-mlp-expansion-factor 0.9 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel 


# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 12 --mixer-mlp-expansion-factor 1.0 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge temporal

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 12 --mixer-mlp-expansion-factor 1.0 --fft-mixer-layer-nr 1 --mixer-representation both --mixer-merge channel 

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 12 --mixer-mlp-expansion-factor 1.0 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge temporal

# sbatch main.py --data-name hapt --shuffle --model-type mixermlp --seed 1 --mixup-argmax --root-path ../../../datasets --filter-scaling-factor  1.0 --mixup-probability 0.5 --random-augmentation-prob 0.5 --random-augmentation-config random_aug_all.yaml --batch-size 128 --mixer-mlp-feature-mum 4 --fft-segments-length 12 --mixer-mlp-expansion-factor 1.0 --fft-mixer-layer-nr 2 --mixer-representation both --mixer-merge channel 


