
eyewall:
  filename: "EyeW_Dataset"
  sampling_freq: 100
  num_classes: 10
  num_channels: 11
  window_seconds: 1.28
  sensors:
  - accel_x  
  - accel_y  
  - accel_z  
  - gyro_x  
  - gyro_y  
  - gyro_z  
  - norm_pos_x  
  - norm_pos_y  
  - gaze_point_3d_x  
  - gaze_point_3d_y  
  - gaze_point_3d_z

eyew:
  filename: "EyeW_Dataset"
  sampling_freq: 100
  num_classes: 10
  num_channels: 6
  window_seconds: 1.28
  sensors:
  - accel_x  
  - accel_y  
  - accel_z  
  - gyro_x  
  - gyro_y  
  - gyro_z  

eye:
  filename: "EyeW_Dataset"
  sampling_freq: 100
  num_classes: 10
  num_channels: 5
  window_seconds: 1.28
  sensors:
  - norm_pos_x  
  - norm_pos_y  
  - gaze_point_3d_x  
  - gaze_point_3d_y  
  - gaze_point_3d_z


mhealth:
  filename: "Mhealth_Dataset"
  sampling_freq: 50
  num_classes: 12
  num_channels: 18
  window_seconds: 2.56
  sensors:
  - acc_left_ankle_x  
  - acc_left_ankle_y  
  - acc_left_ankle_z  
  - gyro_left_ankle_x  
  - gyro_left_ankle_y  
  - gyro_left_ankle_z  
  - mag_left_ankle_x  
  - mag_left_ankle_y  
  - mag_left_ankle_z  
  - acc_right_lower_arm_x  
  - acc_right_lower_arm_y  
  - acc_right_lower_arm_z  
  - gyro_right_lower_arm_x  
  - gyro_right_lower_arm_y  
  - gyro_right_lower_arm_z  
  - mag_right_lower_arm_x  
  - right_lower_arm_y  
  - right_lower_arm_z
  S_number_sensors_type: 3
  L_sensor_locations: 2
  k_number_sensors_group: 6

motionsense:
  filename: "Motion_Sense_Dataset"
  sampling_freq: 50
  num_classes: 6
  num_channels: 12
  window_seconds: 2.56
  sensors:
  - attitude.roll
  - attitude.pitch
  - attitude.yaw
  - gravity.x
  - gravity.y
  - gravity.z
  - rotationRate.x
  - rotationRate.y
  - rotationRate.z
  - userAcceleration.x
  - userAcceleration.y
  - userAcceleration.z
  S_number_sensors_type: 4
  L_sensor_locations: 1
  k_number_sensors_group: 4

hapt:
  filename: "HAPThar_Dataset"
  sampling_freq: 50
  num_classes: 12
  num_channels: 6
  window_seconds: 2.56
  sensors:
  - acc_x_1
  - acc_y_1
  - acc_z_1
  - gyro_x_2
  - gyro_y_2
  - gyro_z_2
  S_number_sensors_type: 2
  L_sensor_locations: 1
  k_number_sensors_group: 2

oppo:
  filename: "Opportunity_Dataset/dataset"
  sampling_freq: 30
  num_classes: 18
  num_channels: 77
  window_seconds: 1
  sensors:
  - acc_x_IBack
  - acc_y_IBack
  - acc_z_IBack
  - gyro_x_IBack
  - gyro_y_IBack
  - gyro_z_IBack
  - magnetic_x_IBack
  - magnetic_y_IBack
  - magnetic_z_IBack
  - acc_x_IRUA
  - acc_y_IRUA
  - acc_z_IRUA
  - gyro_x_IRUA
  - gyro_y_IRUA
  - gyro_z_IRUA
  - magnetic_x_IRUA
  - magnetic_y_IRUA
  - magnetic_z_IRUA
  - acc_x_IRLA
  - acc_y_IRLA
  - acc_z_IRLA
  - gyro_x_IRLA
  - gyro_y_IRLA
  - gyro_z_IRLA
  - magnetic_x_IRLA
  - magnetic_y_IRLA
  - magnetic_z_IRLA
  - acc_x_ILUA
  - acc_y_ILUA
  - acc_z_ILUA
  - gyro_x_ILUA
  - gyro_y_ILUA
  - gyro_z_ILUA
  - magnetic_x_ILUA
  - magnetic_y_ILUA
  - magnetic_z_ILUA
  - acc_x_ILLA
  - acc_y_ILLA
  - acc_z_ILLA
  - gyro_x_ILLA
  - gyro_y_ILLA
  - gyro_z_ILLA
  - magnetic_x_ILLA
  - magnetic_y_ILLA
  - magnetic_z_ILLA
  - EU_x_LSHOE
  - EU_y_LSHOE
  - EU_z_LSHOE
  - acc_x_Nav_LSHOE
  - acc_y_Nav_LSHOE
  - acc_z_Nav_LSHOE
  - acc_x_body_LSHOE
  - acc_y_body_LSHOE
  - acc_z_body_LSHOE
  - AngVel_x_body_LSHOE
  - AngVel_y_body_LSHOE
  - AngVel_z_body_LSHOE
  - AngVel_x_Nav_LSHOE
  - AngVel_y_Nav_LSHOE
  - AngVel_z_Nav_LSHOE
  - Compass_none_LSHOE
  - EU_x_RSHOE
  - EU_y_RSHOE
  - EU_z_RSHOE
  - acc_x_Nav_RSHOE
  - acc_y_Nav_RSHOE
  - acc_z_Nav_RSHOE
  - acc_x_body_RSHOE
  - acc_y_body_RSHOE
  - acc_z_body_RSHOE
  - AngVel_x_body_RSHOE
  - AngVel_y_body_RSHOE
  - AngVel_z_body_RSHOE
  - AngVel_x_Nav_RSHOE
  - AngVel_y_Nav_RSHOE
  - AngVel_z_Nav_RSHOE
  - Compass_none_RSHOE





wisdm:
  filename: "WISDM_Dataset"
  sampling_freq: 20
  num_classes: 6
  num_channels: 3
  window_seconds: 5
  sensors:
  - acc_x_1
  - acc_y_1
  - acc_z_1

dg:
  filename: "Daphnet_Dataset/dataset"
  sampling_freq: 64
  num_classes: 2
  num_channels: 9
  window_seconds: 1
  sensors:
  - acc_x_ankle
  - acc_y_ankle
  - acc_z_ankle
  - acc_x_leg
  - acc_y_leg
  - acc_z_leg
  - acc_x_trunk
  - acc_y_trunk
  - acc_z_trunk
  S_number_sensors_type: 1
  L_sensor_locations: 3
  k_number_sensors_group: 3

uschad:
  filename: "USC_HAD_Dataset"
  sampling_freq: 100
  num_classes: 12
  num_channels: 6
  window_seconds: 1
  sensors:
  - acc_x_1
  - acc_y_1
  - acc_z_1
  - gyro_x_2
  - gyro_y_2
  - gyro_z_2

pamap2:
  filename: "PAMAP2_Dataset/Protocol"
  sampling_freq: 100
  num_classes: 12
  num_channels: 18
  window_seconds: 1.28
  sensors:
  - acc_x_hand
  - acc_y_hand
  - acc_z_hand
  - gyro_x_hand
  - gyro_y_hand
  - gyro_z_hand
  - acc_x_chest
  - acc_y_chest
  - acc_z_chest
  - gyro_x_chest
  - gyro_y_chest
  - gyro_z_chest
  - acc_x_ankle
  - acc_y_ankle
  - acc_z_ankle
  - gyro_x_ankle
  - gyro_y_ankle
  - gyro_z_ankle
  S_number_sensors_type: 2
  L_sensor_locations: 3
  k_number_sensors_group: 6




rw:
  filename: "RWhar_Dataset"
  sampling_freq: 50
  num_classes: 8
  num_channels: 21
  window_seconds: 2.56
  sensors:
  - acc_x_chest
  - acc_y_chest
  - acc_z_chest
  - acc_x_forearm
  - acc_y_forearm
  - acc_z_forearm
  - acc_x_head
  - acc_y_head
  - acc_z_head
  - acc_x_shin
  - acc_y_shin
  - acc_z_shin
  - acc_x_thigh
  - acc_y_thigh
  - acc_z_thigh
  - acc_x_upperarm
  - acc_y_upperarm
  - acc_z_upperarm
  - acc_x_waist
  - acc_y_waist
  - acc_z_waist
  S_number_sensors_type: 1
  L_sensor_locations: 7
  k_number_sensors_group: 7

skodar:
  filename: "Skoda HAR Dataset"
  sampling_freq: 100
  num_classes: 10
  num_channels: 30
  window_seconds: 1.28
  sensors:
  - acc_x_1
  - acc_y_1
  - acc_z_1
  - acc_x_2
  - acc_y_2
  - acc_z_2
  - acc_x_3
  - acc_y_3
  - acc_z_3
  - acc_x_4
  - acc_y_4
  - acc_z_4
  - acc_x_5
  - acc_y_5
  - acc_z_5
  - acc_x_6
  - acc_y_6
  - acc_z_6
  - acc_x_7
  - acc_y_7
  - acc_z_7
  - acc_x_8
  - acc_y_8
  - acc_z_8
  - acc_x_9
  - acc_y_9
  - acc_z_9
  - acc_x_10
  - acc_y_10
  - acc_z_10
  S_number_sensors_type: 1
  L_sensor_locations: 10
  k_number_sensors_group: 10

dsads:
  filename: "DSADS_Dataset"
  sampling_freq: 25
  num_classes: 19
  num_channels: 45
  window_seconds: 5
  sensors:
  - acc_x_T
  - acc_y_T
  - acc_z_T
  - gyro_x_T
  - gyro_y_T
  - gyro_z_T
  - mag_x_T
  - mag_y_T
  - mag_z_T
  - acc_x_RA
  - acc_y_RA
  - acc_z_RA
  - gyro_x_RA
  - gyro_y_RA
  - gyro_z_RA
  - mag_x_RA
  - mag_y_RA
  - mag_z_RA
  - acc_x_LA
  - acc_y_LA
  - acc_z_LA
  - gyro_x_LA
  - gyro_y_LA
  - gyro_z_LA
  - mag_x_LA
  - mag_y_LA
  - mag_z_LA
  - acc_x_RL
  - acc_y_RL
  - acc_z_RL
  - gyro_x_RL
  - gyro_y_RL
  - gyro_z_RL
  - mag_x_RL
  - mag_y_RL
  - mag_z_RL
  - acc_x_LL
  - acc_y_LL
  - acc_z_LL
  - gyro_x_LL
  - gyro_y_LL
  - gyro_z_LL
  - mag_x_LL
  - mag_y_LL
  - mag_z_LL
  S_number_sensors_type: 3
  L_sensor_locations: 5
  k_number_sensors_group: 15



bosch:
  filename: "Bosch_HAR_Dataset"
  sampling_freq: 50
  num_classes: 5
  num_channels: 44
  window_seconds: 2.56
  sensors:
  - rawMagnetometer_iPhone_magn_x
  - rawMagnetometer_iPhone_magn_y
  - rawMagnetometer_iPhone_magn_z
  - deviceMotion_iPhone_roll
  - deviceMotion_iPhone_pitch
  - deviceMotion_iPhone_yaw
  - deviceMotion_iPhone_gravity_x
  - deviceMotion_iPhone_gravity_y
  - deviceMotion_iPhone_garvity_z
  - deviceMotion_iPhone_magneticField_x
  - deviceMotion_iPhone_magneticField_y
  - deviceMotion_iPhone_magneticField_z
  - deviceMotion_iPhone_acc_x
  - deviceMotion_iPhone_acc_y
  - deviceMotion_iPhone_acc_z
  - deviceMotion_iPhone_rotationRate_x
  - deviceMotion_iPhone_rotationRate_y
  - deviceMotion_iPhone_rotationRate_z
  - relAltitude_AppleWatch_pressure
  - location_iPhone_speed
  - deviceMotion_AppleWatch_roll
  - deviceMotion_AppleWatch_pitch
  - deviceMotion_AppleWatch_yaw
  - deviceMotion_AppleWatch_gravity_x
  - deviceMotion_AppleWatch_gravity_y
  - deviceMotion_AppleWatch_garvity_z
  - deviceMotion_AppleWatch_magneticField_x
  - deviceMotion_AppleWatch_magneticField_y
  - deviceMotion_AppleWatch_magneticField_z
  - deviceMotion_AppleWatch_acc_x
  - deviceMotion_AppleWatch_acc_y
  - deviceMotion_AppleWatch_acc_z
  - deviceMotion_AppleWatch_rotationRate_x
  - deviceMotion_AppleWatch_rotationRate_y
  - deviceMotion_AppleWatch_rotationRate_z
  - rawRotationRate_iPhone_acc_x
  - rawRotationRate_iPhone_acc_y
  - rawRotationRate_iPhone_acc_z
  - location_AppleWatch_speed
  - relAltitude_iPhone_pressure
  - rawAccelerometer_iPhone_acc_x
  - rawAccelerometer_iPhone_acc_y
  - rawAccelerometer_iPhone_acc_z
  - WatchWorkout_HeartRate_AppleWatch_HeartRate

gesture:
  filename: "Gesture_Dataset"
  sampling_freq: 200
  num_classes: 12
  num_channels: 18
  window_seconds: 1.5
  sensors:
  - emg1 
  - emg2
  - emg3
  - emg4
  - emg5
  - emg6
  - emg7
  - emg8
  - q1
  - q2
  - q3
  - q4
  - g1
  - g2
  - g3
  - a1
  - a2
  - a3 

sensed:
  filename: "Sensed_Dataset"
  sampling_freq: 75
  num_classes: 26
  num_channels: 6
  window_seconds: 2
  sensors:
  - acc_x 
  - acc_y
  - acc_z
  - gry_x
  - gry_y
  - gry_z

lsign:
  filename: "Language_Gesture_Dataset"
  sampling_freq: 75
  num_classes: 36
  num_channels: 16
  window_seconds: 1
  sensors:
  - P1_1 
  - P1_2
  - P2_1
  - P2_2
  - P3_1
  - P3_2
  - P4_1 
  - P4_2
  - P5_1
  - P5_2
  - Euler_x
  - Euler_y
  - Euler_z
  - Acc_x
  - Acc_y
  - Acc_z

lsignimu:
  filename: "Language_Gesture_Dataset"
  sampling_freq: 75
  num_classes: 36
  num_channels: 6
  window_seconds: 1
  sensors:
  - Euler_x
  - Euler_y
  - Euler_z
  - Acc_x
  - Acc_y
  - Acc_z

lsignpizo:
  filename: "Language_Gesture_Dataset"
  sampling_freq: 75
  num_classes: 36
  num_channels: 10
  window_seconds: 1
  sensors:
  - P1_1 
  - P1_2
  - P2_1
  - P2_2
  - P3_1
  - P3_2
  - P4_1 
  - P4_2
  - P5_1
  - P5_2

geshome:
  filename: "GesHome_dataset"
  sampling_freq: 25
  num_classes: 18
  num_channels: 9
  window_seconds: 2
  sensors:
  - acc_x 
  - acc_y
  - acc_z
  - gyo_x
  - gyo_y
  - gyo_z
  - mag_x 
  - mag_y
  - mag_z
  S_number_sensors_type: 3
  L_sensor_locations: 1
  k_number_sensors_group: 3
  
eeggesture:
  filename: "EEGGesture_Dataset"
  sampling_freq: 50
  num_classes: 7
  num_channels: 8
  window_seconds: 1
  sensors:
  - col_1 
  - col_2
  - col_3
  - col_4
  - col_5
  - col_6
  - col_7 
  - col_8

emggesture:
  filename: "EMGGesture_Dataset"
  sampling_freq: 40
  num_classes: 7
  num_channels: 8
  window_seconds: 1
  sensors:
  - col_1 
  - col_2
  - col_3
  - col_4
  - col_5
  - col_6
  - col_7 
  - col_8

magbreathair:
  filename: "MAG_Breathing_Dataset"
  sampling_freq: 50
  num_classes: 15
  num_channels: 1
  window_seconds: 7.5
  sensors:
  - Airflow (ml) 

jubot:
  filename: "Jubot_HAR_Dataset"
  sampling_freq: 50
  num_channels: 18
  num_classes: 4
  window_seconds: 1
  sensors:
  - Acc_X_1
  - Acc_Y_1
  - Acc_Z_1
  - Gyro_X_1
  - Gyro_Y_1
  - Gyro_Z_1
  - Acc_X_2 
  - Acc_Y_2 
  - Acc_Z_2 
  - Gyro_X_2 
  - Gyro_Y_2 
  - Gyro_Z_2 
  - Acc_X_3 
  - Acc_Y_3 
  - Acc_Z_3 
  - Gyro_X_3 
  - Gyro_Y_3 
  - Gyro_Z_3
  S_number_sensors_type: 2
  L_sensor_locations: 3
  k_number_sensors_group: 6

bciia:
  filename: "BCIIIA_Dataset"
  sampling_freq: 250
  num_classes: 4
  num_channels: 22
  window_seconds: 3
  sensors:
  - col_1
  - col_2
  - col_3
  - col_4
  - col_5
  - col_6
  - col_7
  - col_8
  - col_9
  - col_10
  - col_11
  - col_12
  - col_13
  - col_14
  - col_15
  - col_16
  - col_17
  - col_18
  - col_19
  - col_20
  - col_21
  - col_22

imagery:
  filename: "Imagery_Dataset"
  sampling_freq: 160
  num_classes: 4
  num_channels: 64
  window_seconds: 4
  sensors:
  - col_1
  - col_2
  - col_3
  - col_4
  - col_5
  - col_6
  - col_7
  - col_8
  - col_9
  - col_10
  - col_11
  - col_12
  - col_13
  - col_14
  - col_15
  - col_16
  - col_17
  - col_18
  - col_19
  - col_20
  - col_21
  - col_22
  - col_23
  - col_24
  - col_25
  - col_26
  - col_27
  - col_28
  - col_29
  - col_30
  - col_31
  - col_32
  - col_33
  - col_34
  - col_35
  - col_36
  - col_37
  - col_38
  - col_39
  - col_40
  - col_41
  - col_42
  - col_43
  - col_44
  - col_45
  - col_46
  - col_47
  - col_48
  - col_49
  - col_50
  - col_51
  - col_52
  - col_53
  - col_54
  - col_55
  - col_56
  - col_57
  - col_58
  - col_59
  - col_60
  - col_61
  - col_62
  - col_63
  - col_64