jitter_1:
  sigma: 0.05

jitter_2:
  sigma: 0.1

jitter_3:
  sigma: 0.15

jitter_4:
  sigma: 0.15

magnitude_scaling_1:
  sigma: 0.1

magnitude_scaling_2:
  sigma: 0.2

magnitude_warp_1:
  sigma: 0.2 


magnitude_warp_2:
  sigma: 0.4

moving_average_1:
  ws: 3

moving_average_2:
  ws: 5

moving_average_3:
  ws: 7

moving_average_4:
  ws: 9

slope_adding_1:
  s: 0.2

slope_adding_2:
  s: 0.4

window_warp_1:
  window_ratio_min: 0.1

window_warp_2:
  window_ratio_min: 0.2

time_warp_1:
  sigma: 0.2 

time_warp_2:
  sigma: 0.4
